import fs from 'fs';
import path from 'path';
import { AuditResult } from '../types/config.ts';
import { formatSizeString } from './size.ts';

export class ReportGenerator {
  static generateJsonReport(result: AuditResult, outputPath: string): void {
    const report = {
      meta: {
        version: '1.0.0',
        timestamp: result.timestamp,
        reportType: 'performance-audit',
      },
      summary: {
        budgetStatus: result.budgetStatus,
        totalBundles: result.bundles.length,
        totalSize: result.bundles.reduce((sum, b) => sum + b.size, 0),
        totalGzipSize: result.bundles.reduce((sum, b) => sum + (b.gzipSize || 0), 0),
      },
      bundles: result.bundles,
      lighthouse: result.lighthouse,
      recommendations: result.recommendations,
    };

    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(outputPath, JSON.stringify(report, null, 2));
  }

  static generateHtmlReport(result: AuditResult, outputPath: string): void {
    const html = this.buildHtmlTemplate(result);

    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(outputPath, html);
  }

  private static buildHtmlTemplate(result: AuditResult): string {
    const timestamp = new Date(result.timestamp).toLocaleString();
    const totalSize = result.bundles.reduce((sum, b) => sum + b.size, 0);
    const totalGzipSize = result.bundles.reduce((sum, b) => sum + (b.gzipSize || 0), 0);

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Performance Audit Report</title>
    <style>
        ${this.getCSS()}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>🎯 Performance Audit Report</h1>
            <p class="timestamp">Generated: ${timestamp}</p>
        </header>

        <div class="summary-cards">
            <div class="card ${result.budgetStatus}">
                <h3>Overall Status</h3>
                <div class="status-indicator">
                    ${this.getStatusIcon(result.budgetStatus)} ${result.budgetStatus.toUpperCase()}
                </div>
            </div>
            <div class="card">
                <h3>Total Bundles</h3>
                <div class="metric">${result.bundles.length}</div>
            </div>
            <div class="card">
                <h3>Total Size</h3>
                <div class="metric">${formatSizeString(totalSize)}</div>
                <div class="sub-metric">Gzipped: ${formatSizeString(totalGzipSize)}</div>
            </div>
        </div>

        <section class="section">
            <h2>📦 Bundle Analysis</h2>
            <div class="table-container">
                <table class="bundle-table">
                    <thead>
                        <tr>
                            <th>Bundle</th>
                            <th>Size</th>
                            <th>Gzipped</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${
      result.bundles.map(bundle => `
                            <tr class="${bundle.status}">
                                <td class="bundle-name">${bundle.name}</td>
                                <td>${formatSizeString(bundle.size)}</td>
                                <td>${bundle.gzipSize ? formatSizeString(bundle.gzipSize) : 'N/A'}</td>
                                <td class="status">${this.getStatusIcon(bundle.status)} ${bundle.status}</td>
                            </tr>
                        `).join('')
    }
                    </tbody>
                </table>
            </div>
        </section>

        ${result.lighthouse ? this.buildLighthouseSection(result.lighthouse) : ''}

        ${result.recommendations.length > 0 ? this.buildRecommendationsSection(result.recommendations) : ''}

        <footer class="footer">
            <p>Generated by <strong>perf-audit-cli</strong> v1.0.0</p>
        </footer>
    </div>

    <script>
        ${this.getJavaScript()}
    </script>
</body>
</html>
`;
  }

  private static buildLighthouseSection(lighthouse: any): string {
    return `
        <section class="section">
            <h2>📊 Lighthouse Scores</h2>
            <div class="lighthouse-scores">
                <div class="score-card">
                    <h4>Performance</h4>
                    <div class="score ${this.getScoreClass(lighthouse.performance)}">${lighthouse.performance}</div>
                </div>
                <div class="score-card">
                    <h4>Accessibility</h4>
                    <div class="score ${this.getScoreClass(lighthouse.accessibility || 0)}">${
      lighthouse.accessibility || 'N/A'
    }</div>
                </div>
                <div class="score-card">
                    <h4>Best Practices</h4>
                    <div class="score ${this.getScoreClass(lighthouse.bestPractices || 0)}">${
      lighthouse.bestPractices || 'N/A'
    }</div>
                </div>
                <div class="score-card">
                    <h4>SEO</h4>
                    <div class="score ${this.getScoreClass(lighthouse.seo || 0)}">${lighthouse.seo || 'N/A'}</div>
                </div>
            </div>

            ${
      lighthouse.metrics
        ? `
                <h3>🚀 Core Web Vitals</h3>
                <div class="metrics-grid">
                    <div class="metric-card">
                        <h4>First Contentful Paint</h4>
                        <div class="metric-value">${lighthouse.metrics.fcp}ms</div>
                    </div>
                    <div class="metric-card">
                        <h4>Largest Contentful Paint</h4>
                        <div class="metric-value">${lighthouse.metrics.lcp}ms</div>
                    </div>
                    <div class="metric-card">
                        <h4>Cumulative Layout Shift</h4>
                        <div class="metric-value">${lighthouse.metrics.cls}</div>
                    </div>
                    <div class="metric-card">
                        <h4>Time to Interactive</h4>
                        <div class="metric-value">${lighthouse.metrics.tti}ms</div>
                    </div>
                </div>
            `
        : ''
    }
        </section>
    `;
  }

  private static buildRecommendationsSection(recommendations: string[]): string {
    return `
        <section class="section">
            <h2>💡 Recommendations</h2>
            <ul class="recommendations">
                ${recommendations.map(rec => `<li>${rec}</li>`).join('')}
            </ul>
        </section>
    `;
  }

  private static getStatusIcon(status: string): string {
    switch (status) {
      case 'ok':
        return '✅';
      case 'warning':
        return '⚠️';
      case 'error':
        return '❌';
      default:
        return '●';
    }
  }

  private static getScoreClass(score: number): string {
    if (score >= 90) return 'good';
    if (score >= 75) return 'average';
    return 'poor';
  }

  private static getCSS(): string {
    return `
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }

        .header {
            text-align: center;
            background: white;
            border-radius: 10px;
            padding: 30px;
            margin-bottom: 30px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }

        .header h1 {
            color: #2d3748;
            font-size: 2.5em;
            margin-bottom: 10px;
        }

        .timestamp {
            color: #718096;
            font-size: 1.1em;
        }

        .summary-cards {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }

        .card {
            background: white;
            border-radius: 10px;
            padding: 20px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            text-align: center;
        }

        .card.ok {
            border-left: 5px solid #48bb78;
        }

        .card.warning {
            border-left: 5px solid #ed8936;
        }

        .card.error {
            border-left: 5px solid #f56565;
        }

        .card h3 {
            color: #2d3748;
            margin-bottom: 15px;
            font-size: 1.2em;
        }

        .status-indicator {
            font-size: 1.5em;
            font-weight: bold;
        }

        .metric {
            font-size: 2em;
            font-weight: bold;
            color: #2d3748;
        }

        .sub-metric {
            color: #718096;
            margin-top: 5px;
        }

        .section {
            background: white;
            border-radius: 10px;
            padding: 30px;
            margin-bottom: 30px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }

        .section h2 {
            color: #2d3748;
            margin-bottom: 20px;
            font-size: 1.8em;
        }

        .table-container {
            overflow-x: auto;
        }

        .bundle-table {
            width: 100%;
            border-collapse: collapse;
        }

        .bundle-table th,
        .bundle-table td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #e2e8f0;
        }

        .bundle-table th {
            background: #f7fafc;
            font-weight: 600;
            color: #2d3748;
        }

        .bundle-table tr.ok {
            background: #f0fff4;
        }

        .bundle-table tr.warning {
            background: #fffbf0;
        }

        .bundle-table tr.error {
            background: #fff5f5;
        }

        .bundle-name {
            font-family: 'Monaco', 'Menlo', monospace;
            font-size: 0.9em;
        }

        .status {
            font-weight: 600;
        }

        .lighthouse-scores {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }

        .score-card {
            text-align: center;
            padding: 20px;
            border-radius: 8px;
            background: #f7fafc;
        }

        .score-card h4 {
            color: #2d3748;
            margin-bottom: 10px;
        }

        .score {
            font-size: 3em;
            font-weight: bold;
            border-radius: 50%;
            width: 80px;
            height: 80px;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 auto;
        }

        .score.good {
            background: #48bb78;
            color: white;
        }

        .score.average {
            background: #ed8936;
            color: white;
        }

        .score.poor {
            background: #f56565;
            color: white;
        }

        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
        }

        .metric-card {
            padding: 20px;
            background: #f7fafc;
            border-radius: 8px;
            text-align: center;
        }

        .metric-card h4 {
            color: #2d3748;
            margin-bottom: 10px;
            font-size: 0.9em;
        }

        .metric-value {
            font-size: 1.8em;
            font-weight: bold;
            color: #4a5568;
        }

        .recommendations {
            list-style: none;
        }

        .recommendations li {
            background: #f7fafc;
            padding: 15px;
            border-left: 4px solid #3182ce;
            margin-bottom: 10px;
            border-radius: 0 8px 8px 0;
        }

        .footer {
            text-align: center;
            padding: 20px;
            color: white;
        }

        @media (max-width: 768px) {
            .container {
                padding: 10px;
            }

            .header h1 {
                font-size: 2em;
            }

            .summary-cards {
                grid-template-columns: 1fr;
            }

            .section {
                padding: 20px;
            }
        }
    `;
  }

  private static getJavaScript(): string {
    return `
        // Add interactive features
        document.addEventListener('DOMContentLoaded', function() {
            // Highlight rows on hover
            const rows = document.querySelectorAll('.bundle-table tbody tr');
            rows.forEach(row => {
                row.addEventListener('mouseenter', function() {
                    this.style.transform = 'scale(1.02)';
                    this.style.transition = 'transform 0.2s ease';
                });
                
                row.addEventListener('mouseleave', function() {
                    this.style.transform = 'scale(1)';
                });
            });

            // Add copy functionality for bundle names
            const bundleNames = document.querySelectorAll('.bundle-name');
            bundleNames.forEach(name => {
                name.style.cursor = 'pointer';
                name.title = 'Click to copy';
                name.addEventListener('click', function() {
                    navigator.clipboard.writeText(this.textContent);
                    const originalText = this.textContent;
                    this.textContent = 'Copied!';
                    setTimeout(() => {
                        this.textContent = originalText;
                    }, 1000);
                });
            });
        });
    `;
  }
}
